[package]
name = "flowly-slicer"
version = "0.1.0"
edition = "2024"

[dependencies]
flowly-core ={ workspace = true }
flowly-service ={ workspace = true }
futures ={ workspace = true }
bytes = { workspace = true }
