[package]
name = "flowy-slicer"
version = "0.1.0"
edition = "2024"

[dependencies]
flowy-core ={ workspace = true }
flowy-service ={ workspace = true }
futures ={ workspace = true }
bytes = { workspace = true }
